### ISSUE TITLE
Metadata generation error with 2015-2016 cycle

### ISSUE THREAD

**Issue by codeanticode** [mirador/nhanes#5]
Command: python makemeta.py 2015-2016 Questionnaire data/sources/csv/2015-2016 data/mirador/2015-2016/question.xml_strings
XML validation error:
Traceback (most recent call last):
  File "makemeta.py", line 461, in <module>
    doc = parseString(''.join(xml_strings))
  File "/Users/andres/anaconda3/lib/python3.7/xml/dom/minidom.py", line 1968, in parseString
    return expatbuilder.parseString(string)
  File "/Users/andres/anaconda3/lib/python3.7/xml/dom/expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "/Users/andres/anaconda3/lib/python3.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 847, column 256

**Comment by codeanticode** [comment]
Fixed with https://github.com/mirador/nhanes/pull/6
